owner: canonical
repo: upptime

sites:
  - name: Ubuntu.com
    url: https://ubuntu.com
  - name: Ubuntu.com engage index
    url: https://ubuntu.com/engage
  - name: Ubuntu.com takeovers index
    url: https://ubuntu.com/takeovers
  - name: Ubuntu.com blog
    url: https://ubuntu.com/blog
  - name: Ubuntu.com blog post
    url: https://ubuntu.com/blog/design-and-web-team-summary-29-december-2020
  - name: Ubuntu.com advantage
    url: https://ubuntu.com/pro
  - name: Ubuntu.com tutorials
    url: https://ubuntu.com/tutorials
  - name: Ubuntu.com tutorial
    url: https://ubuntu.com/tutorials/how-to-install-ubuntu-desktop-on-raspberry-pi-4#1-overview
  - name: Ubuntu.com kubernetes docs
    url: https://ubuntu.com/kubernetes/charmed-k8s/docs
  - name: Ubuntu.com Ceph docs
    url: https://ubuntu.com/ceph/docs
  - name: Ubuntu Server docs
    url: https://documentation.ubuntu.com/server/
  - name: Ubuntu.com appliance landing page
    url: https://ubuntu.com/appliance
  - name: Ubuntu.com appliance openhab page
    url: https://ubuntu.com/appliance/openhab
  - name: Ubuntu.com CVE list
    url: https://ubuntu.com/security/cves
  - name: Ubuntu.com CVE page
    url: https://ubuntu.com/security/CVE-2020-15180
  - name: Ubuntu.com USN list
    url: https://ubuntu.com/security/notices
  - name: Ubuntu.com USN page
    url: https://ubuntu.com/security/notices/USN-4697-2
  - name: Ubuntu Security API - CVEs
    url: https://ubuntu.com/security/cves.json
  - name: Ubuntu Security API - Notices
    url: https://ubuntu.com/security/notices.json
  - name: Ubuntu Security API - CVE page
    url: https://ubuntu.com/security/cves/CVE-2020-15180.json
  - name: Ubuntu Security API - USN page
    url: https://ubuntu.com/security/notices/USN-4697-2.json
  - name: Snapcraft.io
    url: https://snapcraft.io
  - name: Snapcraft.io store page
    url: https://snapcraft.io/store
  - name: Charmhub.io
    url: https://charmhub.io
  - name: Vanilla Framework
    url: https://vanillaframework.io
  - name: JAAS.ai
    url: https://jaas.ai
  - name: canonical.com
    url: https://canonical.com
  - name: canonical.com solutions page
    url: https://canonical.com/solutions
  - name: cn.ubuntu.com
    url: https://cn.ubuntu.com
  - name: jp.ubuntu.com
    url: https://jp.ubuntu.com
  - name: juju.is
    url: https://juju.is
  - name: microk8s.io
    url: https://microk8s.io
  - name: microk8s.io/docs
    url: https://microk8s.io/docs/release-notes
  - name: netplan.io
    url: https://netplan.io
  - name: readthedocs index page
    url: https://docs.ubuntu.com/
  - name: Content System
    url: https://cs.canonical.com
  - name: Canonical Design
    url: https://canonical.design
  

status-website:
  baseUrl: /upptime
  logoUrl: https://assets.ubuntu.com/v1/b3b72cb2-canonical-logo-166.png
  name: Canonical websites monitoring
  favicon: https://assets.ubuntu.com/v1/49a1a858-favicon-32x32.png
  introTitle: "**Upptime** monitors the websites that Canonical's webteam manages."
  introMessage: Feel free to visit [our GitHub organisation](https://github.com/canonical) to help us make our websites great!
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/canonical/upptime
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
